#!/bin/bash


RUNUSER=""
SERVERNAME=""
RUNCOMMAND=""


s_status ()
{
  screen -ls | grep --quiet $SERVERNAME
  return $?
}

s_start ()
{
  if se_status
  then
    echo "Server is already running please stop this server before making another."
  else
    echo "Starting $SERVERNAME server."
    screen -S $SERVERNAMEServer -dm bash -c "$RUNCOMMAND"
  fi
}

s_stop ()
{
  if se_status 
  then
    echo "Stopping $SERVERNAME Server."
    screen -S $SERVERNAMEServer -X stuff $'\003'
    screen -S $SERVERNAMEServer -r
  else
    echo "Server isn't running."
  fi
}

s_restart ()
{
  if se_status
  then
    echo "Restarting $SERVERNAME Server."
    s_stop
    s_start
  else
    s_start
  fi
}

s_update ()
{
  
}

s_help ()
{
  cat .help
}


if [ "$(whoami)" != "$RUNUSER" ]
then
  echo You are logged in as $(whoami) but the server can only be started as the $RUNUSER user. Please log in as this user and run this script again.
  exit 1
fi
if [ ! -z "$2" ] 
then
  help
  exit 3
fi 
case $1 in
  start)
	s_start
        ;;
  stop)
	s_stop 
	;;
  restart)
	s_restart 
	;;
  update)
	s_update
	;;
  status)
	if s_status;
	then
		echo "$SERVERNAMEServer is running."
	else
		echo "$SERVERNAMEServer is not running."
	fi
	;;
  help)
	s_help
        ;;
  *)
	s_help
	;;
esac
