#!/bin/bash



se_status ()
{
  screen -ls | grep --quiet SEServer 
  return $?
}

se_start ()
{
  if se_status
  then
    echo "Server is already running please stop this server before making another."
  else
    echo "Starting Space Engineer server."
    screen -S SEServer -dm bash -c "WINEDEBUG=-all wine /home/spaceengineers/.wine/drive_c/users/spaceengineers/Desktop/Tools/DedicatedServer/SpaceEngineersDedicated.exe -console"
  fi
}

se_stop ()
{
  if se_status 
  then
    echo "Stopping Space Engineers Server."
    screen -S SEServer -X stuff $'\003'
    screen -S SEServer -r
  else
    echo "Server isn't running."
  fi
}

se_restart ()
{
  if se_status
  then
    echo "Restarting Space Engineers Server."
    se_stop
    se_start
  else
    se_start
  fi
}

se_update ()
{
  if [ -O update/DedicatedServer.zip ] && [ -O update/ModelPack.zip ]
  then
    mv update/DedicatedServer.zip .wine/drive_c/users/spaceengineers/Desktop/Tools/.
    mv update/ModelPack.zip .wine/drive_c/users/spaceengineers/Desktop/Tools/.
    echo "Updating server files."
    unzip .wine/drive_c/users/spaceengineers/Desktop/Tools/DedicatedServer.zip
    echo "Updating models."
    unzip .wine/drive_c/users/spaceengineers/Desktop/Tools/ModelPack.zip
    echo "Update finished."
  else
    echo "No update files could be found in directory 'update/'."
    if [ ! -d "update" ]
    then
      mkdir update
    fi
  fi
}

help ()
{
  cat .help
}


if [ "$(whoami)" != "spaceengineers" ]
then
  echo You are logged in as $(whoami) but the server can only be started as the spaceengineers user. Please log in as this user and run this script again.
  exit 1
fi
if [ "$(pwd)" != "/home/spaceengineers" ]
then
  echo You can only run this script from your home directory.
  exit 2
fi
if [ ! -z "$2" ] 
then
  help
  exit 3
fi 
case $1 in
  start)
	se_start
        ;;
  stop)
	se_stop 
	;;
  restart)
	se_restart 
	;;
  update)
	se_update
	;;
  status)
	if se_status;
	then
		echo "SEServer is running."
	else
		echo "SEServer is not running."
	fi
	;;
  help)
	help
        ;;
  *)
	help
	;;
esac
